[build-system]
requires = ["setuptools>=69,<74"]
build-backend = "setuptools.build_meta"

[project]
name = "waphl-data"
version = "2.1.3"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.55",
    "pandas>=2.2",
    "boto3>=1.34",
    "s3fs",
    "deltalake>=1.4",
    "requests>=2.32",
    "tqdm>=4.67",
    "jsonschema>=4.23",
    "firecloud>=0.16.39",
    "google-cloud-storage>=2.18",
    "tornado"

]